name: PR Open

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  deployment:
    name: setup
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.18.1'
          kubernetes version: 'v1.20.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: wait
        run: while [[ $(kubectl -n kube-system get pods -l k8s-app=kube-dns -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done
      - name: Install deps
        run: |
          curl -o /tmp/cinc-auditor.deb http://downloads.cinc.sh/files/stable/cinc-auditor/4.37.0/ubuntu/20.04/cinc-auditor_4.37.0-1_amd64.deb
          sudo dpkg -i /tmp/cinc-auditor.deb
      - name: Build
        run: |
          make build
          while [[ $(kubectl get pods -n deployment-example -l app=postgres-master -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]
          do
            echo "waiting for pod" && sleep 1
          done
      - name: TF Destroy
        run: |
          make clean || true
        if: ${{ always() }}
